[package]
name = "ic-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.2"
prost = { workspace = true }
scoped_threadpool = "0.1.*"
serde = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.1.0"
serde = { workspace = true }
