[package]
name = "ic-ethereum-types"
description = "Ethereum common types that are used across multiple crates"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4"
ic-crypto-sha3 = { path = "../../crypto/sha3" }
minicbor = { workspace = true }
minicbor-derive = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.0"
serde_json = { workspace = true }
