[package]
name = "ic-icrc-rosetta-client"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ic-rosetta-api = { path = "../../../" }
ic-icrc-rosetta = { path = "../" }
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
url = "2.2.1"
rosetta-core = {path = "../../../rosetta_core"}
ed25519-consensus = "2.0.1"
hex = "^0.4.2"