[package]
name = "hostos_tool"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "hostos_tool"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = {version = "^4", features = ["derive"]}
config = { path = "../config" }
network = { path = "../network" }
utils = { path = "../utils" }